### ISSUE TITLE
Build error deploying on vercel

### ISSUE THREAD

**Issue by karthikveeramani** [maxwellfortney/next-candy-machine#13]
This runs fine with yarn dev, but while deploying on vercel, I get this build error (which does not appear when I locally run yarn run build):

2021-11-15T16:09:02.616Z  undefined
2021-11-15T16:09:02.625Z  (node:919) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: undefined
2021-11-15T16:09:02.625Z      at new NodeError (internal/errors.js:322:7)
2021-11-15T16:09:02.626Z      at onParseError (internal/url.js:270:9)
2021-11-15T16:09:02.626Z      at new URL (internal/url.js:346:5)
2021-11-15T16:09:02.626Z      at new Connection (/vercel/path0/node_modules/@solana/web3.js/lib/index.cjs.js:3504:15)
2021-11-15T16:09:02.627Z      at Object.730 (/vercel/path0/.next/server/chunks/730.js:30:20)
2021-11-15T16:09:02.627Z      at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
2021-11-15T16:09:02.627Z      at Object.476 (/vercel/path0/.next/server/pages/_app.js:16:81)
2021-11-15T16:09:02.628Z      at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
2021-11-15T16:09:02.628Z      at __webpack_exec__ (/vercel/path0/.next/server/pages/_app.js:145:39)
2021-11-15T16:09:02.628Z      at /vercel/path0/.next/server/pages/_app.js:146:74
2021-11-15T16:09:02.629Z  (Use `node --trace-warnings ...` to show where the warning was created)
2021-11-15T16:09:02.629Z  (node:919) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-11-15T16:09:02.629Z  (node:919) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-11-15T16:09:02.652Z  undefined
2021-11-15T16:09:02.655Z  
2021-11-15T16:09:02.655Z  > Build error occurred
2021-11-15T16:09:02.659Z  TypeError [ERR_INVALID_URL]: Invalid URL: undefined
2021-11-15T16:09:02.659Z      at new NodeError (internal/errors.js:322:7)
2021-11-15T16:09:02.659Z      at onParseError (internal/url.js:270:9)
2021-11-15T16:09:02.659Z      at new URL (internal/url.js:346:5)
2021-11-15T16:09:02.659Z      at new Connection (/vercel/path0/node_modules/@solana/web3.js/lib/index.cjs.js:3504:15)
2021-11-15T16:09:02.660Z      at Object.730 (/vercel/path0/.next/server/chunks/730.js:30:20)
2021-11-15T16:09:02.660Z      at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
2021-11-15T16:09:02.660Z      at Object.476 (/vercel/path0/.next/server/pages/_app.js:16:81)
2021-11-15T16:09:02.660Z      at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
2021-11-15T16:09:02.661Z      at __webpack_exec__ (/vercel/path0/.next/server/pages/_app.js:145:39)
2021-11-15T16:09:02.661Z      at /vercel/path0/.next/server/pages/_app.js:146:74 {
2021-11-15T16:09:02.661Z    type: 'NodeError',
2021-11-15T16:09:02.661Z    input: 'undefined',
2021-11-15T16:09:02.662Z    code: 'ERR_INVALID_URL'
2021-11-15T16:09:02.662Z  }
2021-11-15T16:09:02.715Z  error Command failed with exit code 1.
2021-11-15T16:09:02.716Z  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-11-15T16:09:02.735Z  Error: Command "yarn run build" exited with 1

**Comment by maxwellfortney** [comment]
You didn't add your environment variables to Vercel.
