### ISSUE TITLE
"yarn dev" fails (fedora 36, node version 16.13.0)

### ISSUE THREAD

**Issue by kayalareren** [maxwellfortney/next-candy-machine#21]
yarn run v1.22.17
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/ekayalar/candytest2/next-candy-machine/.env.local
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - automatically enabled Fast Refresh for 1 custom loader
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:138971:18)
    at BulkUpdateDecorator.update (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:138872:50)
    at OriginalSource.updateHash (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack-sources3/index.js:1:10264)
    at NormalModule._initBuildHash (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:68468:17)
    at handleParseResult (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:68534:10)
    at /home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:68628:4
    at processResult (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:68343:11)
    at /home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:68407:5
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:138971:18)
    at BulkUpdateDecorator.update (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:138872:50)
    at OriginalSource.updateHash (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack-sources3/index.js:1:10264)
    at NormalModule._initBuildHash (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:68468:17)
    at handleParseResult (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:68534:10)
    at /home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:68628:4
    at processResult (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:68343:11)
    at /home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:68407:5
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:138971:18)
    at BulkUpdateDecorator.update (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:138872:50)
    at OriginalSource.updateHash (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack-sources3/index.js:1:10264)
    at NormalModule._initBuildHash (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:68468:17)
    at handleParseResult (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:68534:10)
    at /home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:68628:4
    at processResult (/home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:68343:11)
    at /home/ekayalar/candytest2/next-candy-machine/node_modules/next/dist/compiled/webpack/bundle5.js:68407:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by kayalareren** [comment]
Only extra thing I did apart from your guide: Installed yarn into metaplex/js/packages/cli because uploading assets failed, but it was fixed when I installed the yarn into cli.

**Comment by ck256-2000** [comment]
hi there - i belive you are using the wrong version of node
'node -v' to confrim
try 'nvm use 14' to correct

gl
