### ISSUE TITLE
ERROR IN UBUNTU YARN BUILD

### ISSUE THREAD

**Issue by quantium-rock** [maxwellfortney/next-candy-machine#25]
~/next-candy-machine$ yarn build
yarn run v1.22.17
$ next build
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data ..undefined
(node:12069) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: undefined
    at onParseError (internal/url.js:279:9)
    at new URL (internal/url.js:355:5)
    at new Connection (/home/quantium-rock/next-candy-machine/node_modules/@solana/web3.js/lib/index.cjs.js:5122:15)
    at Object.730 (/home/quantium-rock/next-candy-machine/.next/server/chunks/730.js:30:20)
    at __webpack_require__ (/home/quantium-rock/next-candy-machine/.next/server/webpack-runtime.js:25:42)
    at Object.476 (/home/quantium-rock/next-candy-machine/.next/server/pages/_app.js:16:81)
    at __webpack_require__ (/home/quantium-rock/next-candy-machine/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/home/quantium-rock/next-candy-machine/.next/server/pages/_app.js:152:39)
    at /home/quantium-rock/next-candy-machine/.next/server/pages/_app.js:153:74
    at Function.__webpack_require__.X (/home/quantium-rock/next-candy-machine/.next/server/webpack-runtime.js:108:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12069) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
info  - Collecting page data .undefined
(node:12069) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: undefined
    at onParseError (internal/url.js:279:9)
    at new URL (internal/url.js:355:5)
    at new Connection (/home/quantium-rock/next-candy-machine/node_modules/@solana/web3.js/lib/index.cjs.js:5122:15)
    at Object.730 (/home/quantium-rock/next-candy-machine/.next/server/chunks/730.js:30:20)
    at __webpack_require__ (/home/quantium-rock/next-candy-machine/.next/server/webpack-runtime.js:25:42)
    at Object.476 (/home/quantium-rock/next-candy-machine/.next/server/pages/_app.js:16:81)
    at __webpack_require__ (/home/quantium-rock/next-candy-machine/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/home/quantium-rock/next-candy-machine/.next/server/pages/_app.js:152:39)
    at /home/quantium-rock/next-candy-machine/.next/server/pages/_app.js:153:74
    at Function.__webpack_require__.X (/home/quantium-rock/next-candy-machine/.next/server/webpack-runtime.js:108:21)
(node:12069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
info  - Collecting page data .undefined

> Build error occurred
TypeError [ERR_INVALID_URL]: Invalid URL: undefined
    at onParseError (internal/url.js:279:9)
    at new URL (internal/url.js:355:5)
    at new Connection (/home/quantium-rock/next-candy-machine/node_modules/@solana/web3.js/lib/index.cjs.js:5122:15)
    at Object.730 (/home/quantium-rock/next-candy-machine/.next/server/chunks/730.js:30:20)
    at __webpack_require__ (/home/quantium-rock/next-candy-machine/.next/server/webpack-runtime.js:25:42)
    at Object.476 (/home/quantium-rock/next-candy-machine/.next/server/pages/_app.js:16:81)
    at __webpack_require__ (/home/quantium-rock/next-candy-machine/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/home/quantium-rock/next-candy-machine/.next/server/pages/_app.js:152:39)
    at /home/quantium-rock/next-candy-machine/.next/server/pages/_app.js:153:74
    at Function.__webpack_require__.X (/home/quantium-rock/next-candy-machine/.next/server/webpack-runtime.js:108:21) {
  type: 'NodeError',
  input: 'undefined',
  code: 'ERR_INVALID_URL'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by quantium-rock** [comment]
HELP PLEASE

**Comment by quantium-rock** [comment]
I have node 14, yarn, Solana Cli & Metaplex Cli installed in a wsl ubuntu.

Thank you!

**Comment by quantium-rock** [comment]
Also $yarn install correctly and upgraded all packages. I tried to $git pull to last /metaplex version. Been fighting already for 2 days...

**Comment by maxwellfortney** [comment]
1.) you probably don't need to be running yarn build. 

2.) the problem is your environment variables are undefined, as you can see in the error

**Comment by quantium-rock** [comment]
> 1.) you probably don't need to be running yarn build.
> 
> 2.) the problem is your environment variables are undefined, as you can see in the error

**Comment by quantium-rock** [comment]
Thank you @maxwellfortney !

SOLVED! I was compiling on WSL2 ~/mnt/ which give an error.

Also env.local was not well configured.

Good job & thanks for sharing!
